### ISSUE TITLE
Usage of AudienceNetworkAds possibly violates GDPR

### ISSUE THREAD

**Issue by bhm** [kamaravichow/safe-dot-android#4]
As of 72f91238dc18d6c804ed9dfac314be69e6e1e2e3 
There is no setting allowing a user to opt out from profiling.

Currently user is at the mercy of the developer and Facebook.

**Comment by kamaravichow** [comment]
https://stackoverflow.com/a/58350178/10530434

3

I think Facebook handles this in another way.

In order to show relevant ads, the user must have used the Facebook app. If no advertisement is shown, it is because the user has not logged in to the app in the last 30 days.

The user has to have consented to targeted ads from within the Facebook apps.

If those conditions are not met, the ad is not shown

The person using your app or site has turned off targeted advertising in his or her device settings.

You can read more about this in this https://www.facebook.com/business/help/1673395492911956
